const areas = [('Raffles Place, Cecil, Marina'),
  ('Anson, Tanjong Pagar'),
  ('Queenstown, Tiong Bahru, Telok Blangah, Harbourfront'),
  ('Pasir Panjang, Hong Leong Garden, Clementi New Town'),
  ('High Street, Beach Road, Middle Road, Golden Mile'),
  ('Little India'),
  ('Orchard, Cairnhill, River Valley'),
  ('Ardmore, Bukit Timah, Holland Road, Tanglin'),
  ('Watten Estate, Novena, Thomson'),
  ('Balestier, Toa Payoh, Serangoon, Macpherson, Braddell'),
  ('Geylang, Eunos, Katong, Joo Chiat, Amber Road'),
  ('Bedok, Upper East Coast, Eastwood, Kew Drive'),
  ('Loyang, Changi, Tampines, Pasir Ris'),
  ('Serangoon Garden, Hougang, Punggol'),
  ('Bishan, Ang Mo Kio'),
  ('Jurong'),
  ('Hillview, Dairy Farm, Bukit Panjang, Choa Chu Kang'),
  ('Kranji, Woodgrove'),
  ('Upper Thomson, Springleaf, Yishun, Sembawang'),
  ('Seletar')];

export default areas;
